cache:
  enabled: true
  expires_in: 60   # seconds, defaults to 300. Ignored when memory cache store used
  flush_resource_id: document:123456
  store: memory   # possible values are 'memory' and 'memcached'
  
debug: true
  